api_platform:
    mapping:
        paths: [
            '%kernel.project_dir%/src/Entity',
            '%kernel.project_dir%/src/Cms/Model',
            '%kernel.project_dir%/src/Ecommerce/Model'
        ]
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
